# Generated by Django 5.1 on 2024-09-02 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_categories_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='parent',
        ),
    ]
