# Generated by Django 5.1 on 2024-09-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.BooleanField(verbose_name=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.SlugField(),
        ),
    ]
